apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my_job
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my_job
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from ARIZONA
          restartPolicy: OnFailure