apiVersion: v1
kind: Pod
metadata:
  name: nginx-config
spec:
  containers:
    - name: demo
      image: nginx
      command: ["sleep", "3600"]
      env:
        - name: PROXY_ENABLED
          valueFrom:
            configMapKeyRef:
              name: proxy-cf
              key: proxy
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: proxy-cf