apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  namespace: sample
spec:
  containers:
  - name: redis-container
    image: redis:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
        - containerPort: 6379
