apiVersion: v1
kind: PersistentVolume
metadata:
  name: joomla-storage
  namespace: sample
spec:
  capacity:
    storage: 350Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath: 
    path: "/mnt/joomla-storage"