apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-joomla
  namespace: sample
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi